// GENERATED from docs/prototypes/dark_portals/proofs.txt (node solve.js):
// each room's proved plan, replayed against the Dart rules by
// planet_dungeon_dark_black_sun_test.dart.

const Map<String, List<String>> kBlackSunPlans = {
  'sun_porch': [
    'light west',
    'orange west',
    'purple casts I east',
    'purple casts II west',
    'purple west (through purple)',
    'light south',
    'purple north',
    'light west (through purple)',
    'light west',
    'light north',
    'light west',
    'purple west',
    'orange north',
    'orange west (through purple)',
    'orange north',
  ],
  'through_the_dark': [
    'light south',
    'light south',
    'light west',
    'purple east',
    'purple east',
    'purple south',
    'purple south',
    'orange east',
    'orange east',
    'orange east',
    'orange south',
    'orange south',
    'orange south',
    'light shines east',
    'purple casts I east',
    'purple south',
    'purple casts II south',
    'purple south (through purple)',
    'purple south',
    'light east',
    'light east',
    'light east',
    'light east',
    'light south',
    'purple east',
    'purple east',
    'purple north',
    'purple casts I west',
    'purple north',
    'light south (through purple)',
    'light south',
    'orange east',
    'orange south (through purple)',
  ],
  'two_darks': [
    'purple south',
    'purple west',
    'purple west',
    'purple west',
    'purple casts I east',
    'light south',
    'purple south',
    'purple casts II south',
    'purple south (through purple)',
    'purple south',
    'orange south',
    'orange east (through purple)',
    'light east',
    'orange casts I north',
    'orange east',
    'light east (through purple)',
    'light north',
    'orange east',
    'light shines east',
    'orange casts II south',
    'orange east',
    'light south',
    'light south (through purple)',
    'purple south',
    'light south',
    'purple south',
    'light south',
    'purple west',
    'light south',
    'purple west',
    'light west',
    'orange east',
    'orange east',
    'orange south',
    'orange south',
  ],
  'sun_hall': [
    'light north',
    'light east',
    'light east',
    'purple north',
    'purple west',
    'purple west',
    'purple casts I south',
    'purple east',
    'purple east',
    'orange west',
    'purple east',
    'orange west',
    'orange west',
    'orange west',
    'orange casts I north',
    'orange east',
    'orange east',
    'orange casts II east',
    'orange north',
    'purple casts II north',
    'purple north',
    'purple north',
    'purple north',
    'purple east',
    'light west',
    'orange east',
    'orange north',
    'light west',
    'orange north',
    'orange east',
    'light north',
    'light north',
    'light north',
    'purple casts II east',
    'purple east',
    'light east',
    'purple east',
    'purple north',
    'light east',
    'light east',
    'orange north',
    'orange east',
    'purple north',
    'light north',
    'orange east',
    'purple east',
    'light north',
    'orange north',
  ],
  'into_the_light': [
    'purple north',
    'purple west',
    'purple casts I east',
    'purple casts II south',
    'purple east',
    'orange casts I west',
    'orange north',
    'light north',
    'orange casts II east',
    'purple north',
    'light west (through orange)',
    'light north',
    'light north',
    'purple east',
    'purple east',
    'purple east',
    'purple east',
    'purple east',
    'purple east',
    'purple north',
    'purple north',
    'purple east',
    'orange east',
    'orange east',
    'orange east',
    'orange east',
    'orange east',
    'orange east',
    'orange east',
    'orange east',
    'orange north',
    'orange north',
  ],
  'hold_the_light': [
    'light west',
    'orange north',
    'orange casts I east',
    'orange north',
    'orange casts II south',
    'purple west',
    'orange east',
    'purple casts I north',
    'purple east',
    'light east',
    'light north',
    'light north',
    'purple east',
    'purple east',
    'light shines east',
    'purple casts II south',
    'purple east',
    'purple east',
    'purple east',
    'purple east',
    'light north',
    'purple east',
    'purple north',
    'purple north',
    'purple east',
    'purple casts II west',
    'light north (through purple)',
    'light north',
    'light east',
    'orange west',
    'orange north (through purple)',
    'orange north',
  ],
  // THE RITE across two rooms (the Lantern and the Heart) — by hand, and
  // replayed against the multi-room rules (the prototype is one room at a
  // time).
  'sun_rite': [
    'light south',
    'light south',
    'light west',
    'light west',
    'light west',
    'light shines south',
    'purple south',
    'purple casts I east',
    'purple south',
    'purple south',
    'purple east',
    'purple south',
    'purple takes the door to sun_heart',
    'purple south',
    'purple west',
    'purple west',
    'purple west',
    'purple casts II west',
    'purple north',
    'orange south',
    'orange south',
    'orange south',
    'orange west',
    'orange south',
    'orange takes the door to sun_heart',
    'orange south',
    'orange casts I east',
    'orange west',
    'orange north',
    'orange casts II north',
    'orange east',
    'orange south',
    'purple east',
    'purple east',
    'purple east',
    'purple north',
    'purple takes the door to sun_lantern',
    'purple casts I west',
    'purple south',
    'purple takes the door to sun_heart',
    'light south',
    'light west',
    'light west',
    'orange south',
    'orange south',
    'orange south',
    'orange south',
    'orange east',
    'purple south',
    'purple south',
    'purple south',
    'purple south',
    'purple south',
    'purple west',
    'light east',
    'light east',
    'light east',
    'light south',
    'light south',
    'light south',
    'light south',
  ],
  'sun_hall_vault': [
    'purple west',
    'purple west',
    'purple casts I south',
    'purple east',
    'purple east',
    'orange casts I east',
    'orange north',
    'orange west',
    'orange west',
    'orange west',
    'purple north',
    'purple east',
    'orange west',
    'purple casts II north',
    'orange casts II north',
    'orange east',
    'purple north',
    'purple casts II west',
    'orange south [purple fell]',
    'orange west',
    'orange south (through purple)',
  ],
};
