@Tags(['preview'])
library;

import 'dart:convert';
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

// Writes lib/games/wilderness/creature_feet.dart: where each species' feet
// sit in its animation frames, so a field can stand it on a rock or a slope
// by its own sprite rather than a guess. Rerun when sprites change:
//
//   FEET_GEN=1 flutter test test/creature_feet_gen_test.dart --tags preview
void main() {
  testWidgets('generate creature feet table', (tester) async {
    if (Platform.environment['FEET_GEN'] != '1') return;
    final json =
        jsonDecode(
              File('assets/data/alchemons_creatures.json').readAsStringSync(),
            )
            as Map<String, dynamic>;
    final feet = <String, double>{};
    await tester.runAsync(() async {
      for (final entry in json['creatures'] as List) {
        final c = entry as Map<String, dynamic>;
        final sprite = c['spriteData'] as Map<String, dynamic>?;
        final image = c['image'] as String?;
        if (sprite == null || image == null) continue;
        final path =
            'assets/images/${image.replaceAll('.png', '_spritesheet.png')}';
        final ByteData data;
        try {
          data = await rootBundle.load(path);
        } catch (_) {
          continue;
        }
        final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
        final sheet = (await codec.getNextFrame()).image;
        final fw = (sprite['frameWidth'] as num).toDouble();
        final fh = (sprite['frameHeight'] as num).toDouble();
        final total = sprite['totalFrames'] as int;
        final rows = (sprite['rows'] as int?) ?? 1;
        final cols = (total + rows - 1) ~/ rows;
        // Read each frame at 200 px tall: plenty to place feet.
        const h = 200;
        final w = (fw / fh * h).round();
        final bottoms = <double>[];
        for (var i = 0; i < total; i++) {
          final src = Rect.fromLTWH((i % cols) * fw, (i ~/ cols) * fh, fw, fh);
          final rec = ui.PictureRecorder();
          Canvas(rec).drawImageRect(
            sheet,
            src,
            Rect.fromLTWH(0, 0, w.toDouble(), h.toDouble()),
            Paint()..filterQuality = FilterQuality.medium,
          );
          final frame = rec.endRecording().toImageSync(w, h);
          final px = (await frame.toByteData(
            format: ui.ImageByteFormat.rawStraightRgba,
          ))!.buffer.asUint8List();
          var bottom = -1;
          for (var y = h - 1; y >= 0 && bottom < 0; y--) {
            for (var x = 0; x < w; x++) {
              if (px[(y * w + x) * 4 + 3] > 110) {
                bottom = y;
                break;
              }
            }
          }
          if (bottom >= 0) bottoms.add((bottom + 1) / h);
        }
        if (bottoms.isEmpty) continue;
        bottoms.sort();
        feet[c['id'] as String] = bottoms[bottoms.length ~/ 2] - 0.5;
      }
    });
    final ids = feet.keys.toList()..sort();
    final out = StringBuffer()
      ..writeln(
        '// GENERATED by test/creature_feet_gen_test.dart. Do not edit.',
      )
      ..writeln()
      ..writeln(
        "/// How far below a creature's frame centre its feet sit, as a",
      )
      ..writeln(
        '/// share of the frame height (the median over its idle frames).',
      )
      ..writeln('const Map<String, double> kCreatureFeet = {');
    for (final id in ids) {
      out.writeln("  '$id': ${feet[id]!.toStringAsFixed(3)},");
    }
    out
      ..writeln('};')
      ..writeln()
      ..writeln('/// [kCreatureFeet] for [speciesId], or a typical sprite.')
      ..writeln('double creatureFeetDrop(String speciesId) =>')
      ..writeln('    kCreatureFeet[speciesId] ?? 0.46;');
    File('lib/games/wilderness/creature_feet.dart').writeAsStringSync('$out');
    // ignore: avoid_print
    print('feet for ${feet.length} species');
  });
}
