// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_UqWBggl4ihGhXIGV0dL9erqwABZu50o',
    appId: '1:78179819122:web:037473ba59772e667caceb',
    messagingSenderId: '78179819122',
    projectId: 'alchemons-auth',
    authDomain: 'alchemons-auth.firebaseapp.com',
    storageBucket: 'alchemons-auth.firebasestorage.app',
    measurementId: 'G-9HJSJW0E1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyJETaDHCzoDdScQ0qnzPvGo7kwyYS1gk',
    appId: '1:78179819122:android:3135ec6939c5f6057caceb',
    messagingSenderId: '78179819122',
    projectId: 'alchemons-auth',
    storageBucket: 'alchemons-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMseGzgITF6zu8gNviAXZ1al6DQGEK7dc',
    appId: '1:78179819122:ios:8f53643106294f087caceb',
    messagingSenderId: '78179819122',
    projectId: 'alchemons-auth',
    storageBucket: 'alchemons-auth.firebasestorage.app',
    iosBundleId: 'com.luck3yapps.alchemons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMseGzgITF6zu8gNviAXZ1al6DQGEK7dc',
    appId: '1:78179819122:ios:2ae02bccde88e5e17caceb',
    messagingSenderId: '78179819122',
    projectId: 'alchemons-auth',
    storageBucket: 'alchemons-auth.firebasestorage.app',
    iosBundleId: 'com.example.alchemons',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_UqWBggl4ihGhXIGV0dL9erqwABZu50o',
    appId: '1:78179819122:web:b4f21ca5e7e4dbd37caceb',
    messagingSenderId: '78179819122',
    projectId: 'alchemons-auth',
    authDomain: 'alchemons-auth.firebaseapp.com',
    storageBucket: 'alchemons-auth.firebasestorage.app',
    measurementId: 'G-50BGG4S501',
  );

}
