// tool/build_dungeon_shaders.dart
//
// Assembles dungeon background shaders. Flutter runtime-effect shaders can't
// #include custom .glsl, so we author shared helpers in
// assets/shaders/dungeon/common/*.glsl and per-element bodies in
// assets/shaders/dungeon/elements/<name>.src.frag, then concatenate them into
// self-contained shaders under assets/shaders/dungeon/built/<name>.frag (the
// files shipped + listed in pubspec).
//
// Run:  dart run tool/build_dungeon_shaders.dart

import 'dart:io';

void main() {
  final commonDir = Directory('assets/shaders/dungeon/common');
  final elementsDir = Directory('assets/shaders/dungeon/elements');
  final outDir = Directory('assets/shaders/dungeon/built')
    ..createSync(recursive: true);

  final commonFiles = commonDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.glsl'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final header = commonFiles.map((f) => f.readAsStringSync().trim()).join('\n\n');

  final sources = elementsDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.src.frag'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  if (sources.isEmpty) {
    stderr.writeln('No *.src.frag found in ${elementsDir.path}');
    exitCode = 1;
    return;
  }

  for (final src in sources) {
    final name =
        src.uri.pathSegments.last.replaceAll('.src.frag', '');
    final body = src.readAsStringSync().trim();
    final out = File('${outDir.path}/$name.frag');
    out.writeAsStringSync(
      '// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.\n'
      '// Edit assets/shaders/dungeon/elements/$name.src.frag or '
      'common/*.glsl, then re-run the tool.\n\n'
      '$header\n\n'
      '$body\n',
    );
    stdout.writeln('built ${out.path}');
  }
}
