// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/air.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// AIR — GAS family. Slow vertical sky currents, drifting cloud veils, faint
// star anchors. Body only: the shared header/helpers are prepended by
// tool/build_dungeon_shaders.dart. Uses uColorA (zenith), uColorB (horizon),
// uColorC (cloud highlight).
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  // Base vertical sky gradient (zenith -> horizon).
  vec3 base = mix(uColorA, uColorB, smoothstep(0.0, 1.0, uv.y));

  // Two layers of drifting cloud veils.
  vec2 q1 = p * uNoiseScale + vec2(t * 0.06, -t * 0.10) + uSeed;
  vec2 q2 = p * uNoiseScale * 2.1 + vec2(-t * 0.12, -t * 0.20) + uSeed * 1.7;
  float clouds = fbm(q1) * 0.65 + fbm(q2) * 0.35;
  float veil = smoothstep(0.45, 0.95, clouds);
  vec3 col = mix(base, uColorC, veil * 0.55 * uIntensity);

  // Soft vertical light shafts.
  float shafts = 0.5 + 0.5 * sin(p.x * 6.0 + t * 0.4 + fbm(q1) * 3.0);
  col += uColorC * shafts * 0.04 * uIntensity;

  // Faint twinkling stars — soft round points, not filled cells.
  vec2 g = p * 80.0;
  vec2 cell = floor(g);
  vec2 fp = fract(g);
  float rnd = hash(cell + uSeed);
  float isStar = step(0.993, rnd);
  vec2 sp = vec2(hash(cell + 1.3), hash(cell + 2.7));
  float d = length(fp - sp);
  float star = isStar * smoothstep(0.10, 0.0, d);
  float tw = 0.5 + 0.5 * sin(t * 3.0 + rnd * 30.0);
  col += vec3(0.8, 0.85, 1.0) * star * tw * 0.5 * (1.0 - uv.y * 0.4);

  fragColor = vec4(col, 1.0);
}
