// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/blood.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// BLOOD — Hemavorn, the Sanguine Orrery. The planet runs on a four-phase
// pulse, so the background BEATS: a systolic surge washes outward, the field
// brightens with it, and thick vessels swell and subside. The vessels are
// deliberately unlike Lightning's veins — slow, smooth, warm and thick, with
// no flicker and no forking filaments, because the two would otherwise be the
// same effect twice. uColorA venous dark, uColorB arterial red,
// uColorC oxygen bright.
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  // THE BEAT — one cycle, with a sharp systole and a long slack diastole,
  // shaped so it lands like a heartbeat rather than a sine wave.
  float cyc = fract(t * 0.32);
  float beat = exp(-cyc * 7.0) + 0.55 * exp(-fract(cyc + 0.86) * 11.0);

  vec3 col = mix(uColorA, uColorB * 0.42, smoothstep(1.1, 0.0, uv.y));

  // Vessels: thick smooth tubes, warped slowly. Wide smoothstep bands, not
  // ridged filaments — the difference from Lightning is the WIDTH and the
  // absence of any high-frequency flicker.
  vec2 vq = p * uNoiseScale * 1.1 + uSeed;
  vq += vec2(fbm(vq * 0.7), fbm(vq.yx * 0.7 + 4.0)) * 1.1;
  float field = fbm(vq);
  // Two nested bands give a dark wall and a brighter lumen inside it.
  float wall = smoothstep(0.20, 0.10, abs(field - 0.5));
  float lumen = smoothstep(0.10, 0.02, abs(field - 0.5));
  col = mix(col, uColorB * 0.8, wall * 0.55);
  col = mix(col, uColorB * 1.35, lumen * (0.5 + 0.5 * beat));

  // The surge itself: a wave travelling out from the heart on every beat.
  vec2 heart = vec2(0.5 * aspect, 0.5);
  float r = length(p - heart);
  float wave = smoothstep(0.10, 0.0, abs(r - cyc * 1.4)) * (1.0 - cyc);
  col += uColorC * wave * 0.35 * uIntensity;

  // Whole-field flush — the room itself pinks up as the pressure arrives.
  col += uColorB * beat * 0.14 * uIntensity;

  // Corpuscles carried along, faster while the pressure is high.
  vec2 gg = vec2(p.x - t * 0.05, p.y + sin(t * 0.4 + p.x * 3.0) * 0.03) * 32.0;
  vec2 cc = floor(gg);
  float rr = hash(cc + uSeed);
  float dd = length(fract(gg) - vec2(hash(cc + 3.9), hash(cc + 8.4)));
  col += uColorC * step(0.980, rr) * smoothstep(0.09, 0.0, dd)
       * (0.35 + 0.65 * beat) * 0.4;

  // Tight vignette — you are inside something.
  col *= 1.0 - smoothstep(0.42, 1.0, length(uv - 0.5)) * 0.52;
  fragColor = vec4(col, 1.0);
}
