// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/crystal.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// CRYSTAL — Lumishara, the Prism Labyrinth. Seen from inside a cut stone:
// hard faceted planes, and light SPLIT into its colours along their edges.
// The dispersion is the signature and it belongs to no other planet; keep the
// geometry angular so it cannot be read as Water's caustics.
// uColorA stone dark, uColorB lattice violet, uColorC white refraction.
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  vec3 col = mix(uColorA, uColorB * 0.5, smoothstep(1.0, 0.0, uv.y));

  // Facets: quantised cells with straight boundaries. Each catches the light
  // differently, and the whole lattice turns very slowly.
  float ang = t * 0.06;
  mat2 rot = mat2(cos(ang), -sin(ang), sin(ang), cos(ang));
  vec2 fp = rot * p * uNoiseScale * 2.0;
  vec2 cell = floor(fp);
  float face = hash(cell + uSeed);
  col = mix(col, uColorB * (0.5 + 0.9 * face), 0.3);

  // Facet EDGES, bright and hard — this is what makes it read as cut stone.
  vec2 f = fract(fp);
  float edge = min(min(f.x, 1.0 - f.x), min(f.y, 1.0 - f.y));
  col += uColorC * smoothstep(0.06, 0.0, edge) * 0.22;

  // DISPERSION. One travelling wavefront, sampled at three slightly different
  // offsets and written to r/g/b separately, so the light splits into a
  // spectrum exactly where it crosses an edge.
  float w = dot(p, vec2(0.8, 0.6)) * 3.0 - t * 0.7;
  float rr = pow(0.5 + 0.5 * sin(w), 22.0);
  float gg = pow(0.5 + 0.5 * sin(w - 0.22), 22.0);
  float bb = pow(0.5 + 0.5 * sin(w - 0.44), 22.0);
  col += vec3(rr, gg, bb) * (0.35 + 0.4 * face) * uIntensity;

  // Sharp specular glints where facets meet — brief, small, star-shaped.
  vec2 sg = fp * 1.5;
  vec2 sc = floor(sg);
  float sr = hash(sc + 9.4);
  vec2 d2 = abs(fract(sg) - vec2(hash(sc + 2.1), hash(sc + 5.6)));
  float star = smoothstep(0.16, 0.0, d2.x + d2.y * 3.0)
             + smoothstep(0.16, 0.0, d2.y + d2.x * 3.0);
  col += uColorC * step(0.985, sr) * star
       * (0.4 + 0.6 * sin(t * 2.2 + sr * 30.0)) * 0.4;

  col *= 1.0 - smoothstep(0.6, 1.05, length(uv - 0.5)) * 0.3;
  fragColor = vec4(col, 1.0);
}
