// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/dark.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// DARK — Nythralor, the Eclipse Vault. An eclipse held at the moment of
// totality: a black disc with a corona burning around its rim, shadow bands
// rippling across everything, and the few stars that come out when the light
// goes. Mostly EMPTY on purpose — the planet is about what is not there, and
// a busy background would argue with that. uColorA void, uColorB umbral
// indigo, uColorC corona white.
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  vec3 col = uColorA;

  // Stars, sparse and cold — only visible because the light is blocked.
  vec2 sg = p * 40.0;
  vec2 sc = floor(sg);
  float sr = hash(sc + uSeed);
  float sd = length(fract(sg) - vec2(hash(sc + 5.1), hash(sc + 8.6)));
  col += uColorC * step(0.986, sr) * smoothstep(0.08, 0.0, sd)
       * (0.5 + 0.5 * sin(t * 1.1 + sr * 30.0)) * 0.45;

  // THE ECLIPSE. A disc high in the frame, and the corona is a thin ring just
  // outside its edge — narrow, so it reads as light escaping past an obstacle
  // rather than as a glow source.
  vec2 c = vec2(0.5 * aspect, 0.34);
  float r = length(p - c);
  float disc = 0.20;
  float ring = smoothstep(0.055, 0.0, abs(r - disc));
  // The corona is uneven and it seethes.
  float seethe = 0.7 + 0.6 * fbm(vec2(atan(p.y - c.y, p.x - c.x) * 3.0, t * 0.4));
  col += uColorC * ring * seethe * 0.75 * uIntensity;
  // Faint outer bloom, falling off fast.
  col += uColorB * smoothstep(disc * 2.6, disc, r) * 0.28;
  // The disc itself takes light AWAY — nothing shows through it.
  col *= 1.0 - smoothstep(disc + 0.012, disc - 0.012, r) * 0.96;

  // SHADOW BANDS: the fine parallel ripples that cross the ground at
  // totality. Thin, fast, and low contrast.
  float bands = sin((p.x * 0.7 + p.y * 1.6) * 55.0 + t * 2.2);
  col += uColorB * smoothstep(0.85, 1.0, bands) * 0.06;

  // Umbral haze pooling at the bottom of the frame.
  col = mix(col, uColorB * 0.6,
            smoothstep(0.55, 1.0, uv.y) * fbm(p * uNoiseScale + 47.0) * 0.35);

  col *= 1.0 - smoothstep(0.45, 1.0, length(uv - 0.5)) * 0.5;
  fragColor = vec4(col, 1.0);
}
