// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/dust.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// DUST — Cindrath, the Ruins of Time. A buried city under a dry sky: the air
// is full of suspended grit lying in horizontal strata, the light is bleached
// and flat, and sheets of wind-driven dust cross the frame. Everything is
// LAYERED, because the whole planet is about what is buried under what.
// uColorA buried dark, uColorB ochre, uColorC bleached bone.
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  // Bleached above, buried below — the horizon of a half-excavated city.
  vec3 col = mix(uColorB, uColorA, smoothstep(0.1, 1.0, uv.y));

  // STRATA. Sharp horizontal banding is the signature: each layer is a
  // different age of dust, and the quantisation makes the boundaries read as
  // deposition lines rather than as noise.
  float depth = uv.y * 7.0 + fbm(vec2(p.x * 1.2, uv.y * 2.0)) * 1.2;
  float band = floor(depth);
  float shade = 0.78 + 0.30 * hash(vec2(band, 3.0));
  col *= shade;
  // A thin bright line at each boundary — the seam between two burials.
  col += uColorC * smoothstep(0.06, 0.0, abs(fract(depth) - 0.5) - 0.44) * 0.10;

  // Wind sheets crossing left to right, dragging grit with them.
  float sheet = fbm(vec2(p.x * 1.8 - t * 0.35, p.y * 4.5) * uNoiseScale * 0.6);
  col = mix(col, uColorC * 0.8, smoothstep(0.55, 0.95, sheet) * 0.28);

  // Suspended grit — dense, fine, and it drifts sideways rather than falling,
  // because this air never settles.
  for (int layer = 0; layer < 2; layer++) {
    float fl = float(layer);
    float scale = 50.0 + fl * 34.0;
    vec2 gg = vec2(p.x - t * (0.10 + fl * 0.07), p.y + t * 0.01) * scale;
    vec2 cc = floor(gg);
    float rr = hash(cc + uSeed + fl * 3.3);
    float dd = length(fract(gg) - vec2(hash(cc + 1.9), hash(cc + 6.4)));
    col += uColorC * step(0.972, rr) * smoothstep(0.11, 0.0, dd)
         * (0.22 - fl * 0.08) * uIntensity;
  }

  // Dry haze washing the whole frame out — this planet has no wet colour.
  col = mix(col, uColorC, 0.06);
  col *= 1.0 - smoothstep(0.55, 1.05, length(uv - 0.5)) * 0.38;
  fragColor = vec4(col, 1.0);
}
