// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/lava.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// LAVA — Magmora, the Molten Reliquary. A FOUNDRY, not a cathedral: this must
// read nothing like fire.frag's soft candlelight (§5.5 visual grammar rule).
// Everything here is horizontal and hard-edged — molten runnels crossing the
// dark in straight bands, a crusted basalt skin cracking over them, white-hot
// where the metal is thinnest, with heat shimmer above and sparks rising off
// the pour. uColorA basalt dark, uColorB molten orange, uColorC white-hot.
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  // Heat shimmer: the whole field is sampled through a rising distortion, so
  // the runnels wobble the way air does over hot metal.
  float shim = fbm(vec2(p.x * 3.0, p.y * 6.0 - t * 0.5)) - 0.5;
  vec2 sp = p + vec2(shim * 0.02, 0.0);

  vec3 col = uColorA;

  // Three molten runnels crossing the frame. Straight lines, not plumes — the
  // works are plumbing, and plumbing is engineered.
  for (int i = 0; i < 3; i++) {
    float fi = float(i);
    float yb = 0.24 + fi * 0.26;
    // A slow sag along the run so it is not a ruler-straight cut.
    float sag = (fbm(vec2(sp.x * 1.6 + fi * 5.0, fi * 2.0)) - 0.5) * 0.06;
    float d = abs(sp.y - (yb + sag));
    // Metal flows LEFT TO RIGHT along the line — the pour has a direction.
    float flow = fbm(vec2(sp.x * 3.5 - t * (0.55 + fi * 0.12), fi * 9.0));
    float body = smoothstep(0.055, 0.0, d);
    float core = smoothstep(0.016, 0.0, d);
    col = mix(col, uColorB, body * (0.55 + 0.45 * flow));
    col = mix(col, uColorC, core * (0.5 + 0.5 * flow) * uIntensity);
  }

  // Crusted skin: a dark cellular crazing laid OVER the glow, so the runnels
  // read as metal cooling rather than as light sources.
  float crust = fbm(sp * uNoiseScale * 3.2 + 11.0);
  col *= 1.0 - smoothstep(0.62, 0.86, crust) * 0.45;

  // Sparks off the pour — sparse, fast, and they rise then die.
  for (int layer = 0; layer < 2; layer++) {
    float fl = float(layer);
    float scale = 42.0 + fl * 26.0;
    vec2 gg = vec2(p.x, p.y + t * (0.30 + fl * 0.18)) * scale;
    vec2 cc = floor(gg);
    float rr = hash(cc + uSeed + fl * 4.7);
    float isSpark = step(0.988, rr);
    vec2 mp = vec2(hash(cc + 2.3), hash(cc + 5.9));
    float dd = length(fract(gg) - mp);
    float life = 0.5 + 0.5 * sin(t * 6.0 + rr * 30.0);
    col += uColorC * isSpark * smoothstep(0.08, 0.0, dd) * life * 0.5;
  }

  // The works are roofed — heavy vignette, heaviest at the top.
  col *= 1.0 - smoothstep(0.35, 1.0, length(uv - vec2(0.5, 0.62))) * 0.5;
  fragColor = vec4(col, 1.0);
}
