// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/mud.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// MUD — Mireholm, the Sinking Altar. Wet, heavy and SLOW. The fen is mostly
// standing water under a low mist, so the motion here is sluggish surface
// drift and the occasional gout of swamp gas — never a flow and never a
// flicker (§5.5: nothing like Steam's tile floods). uColorA peat dark,
// uColorB silt brown, uColorC pale mist.
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  vec3 col = mix(uColorA, uColorB, smoothstep(1.1, 0.1, uv.y));

  // Standing water: two very slow counter-drifting sheets, warped into each
  // other so the surface stirs without ever appearing to travel.
  vec2 w1 = p * uNoiseScale * 1.4 + vec2(t * 0.035, t * 0.012);
  vec2 w2 = p * uNoiseScale * 0.9 - vec2(t * 0.022, t * 0.008) + 17.0;
  float sheet = fbm(w1 + fbm(w2) * 0.8);
  col = mix(col, uColorB * 1.25, smoothstep(0.45, 0.85, sheet) * 0.42);

  // Silt suspended in it — darker blotches that make the water look thick.
  col *= 1.0 - smoothstep(0.55, 0.9, fbm(p * uNoiseScale * 2.6 + 41.0)) * 0.3;

  // Swamp gas: a slow gout that swells and releases. Low frequency, so the
  // fen feels like it is breathing rather than fizzing.
  vec2 gg = vec2(p.x, p.y + t * 0.04) * 18.0;
  vec2 cc = floor(gg);
  float rr = hash(cc + uSeed);
  float phase = fract(t * 0.18 + rr);
  float dd = length(fract(gg) - vec2(hash(cc + 2.9), hash(cc + 7.3)));
  float gout = step(0.982, rr) * smoothstep(0.02 + phase * 0.08, 0.0, dd)
             * (1.0 - phase);
  col += uColorC * gout * 0.4;

  // Ground mist lying ON the water — a flat band low in the frame, drifting
  // sideways. This is the only fast-ish motion, and it is still gentle.
  float mist = fbm(vec2(p.x * 1.5 - t * 0.09, p.y * 5.0) + 63.0);
  col = mix(col, uColorC, smoothstep(0.5, 0.95, mist)
                          * smoothstep(0.45, 1.0, uv.y) * 0.3);

  col *= 1.0 - smoothstep(0.5, 1.0, length(uv - 0.5)) * 0.45;
  fragColor = vec4(col, 1.0);
}
