// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/plant.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// PLANT — Verdanthos, the Verdant Crypt. Under a canopy: shafts of green-gold
// light coming down through leaves that move, dappling everything below, with
// pollen turning slowly in the beams. Soft and organic — the deliberate
// opposite of Crystal's hard facets, and warmer than Poison's flat miasma.
// uColorA loam dark, uColorB leaf green, uColorC sun gold.
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  // Light comes from ABOVE and dies before it reaches the floor.
  vec3 col = mix(uColorB * 0.45, uColorA, smoothstep(0.0, 1.0, uv.y));

  // The canopy itself: a slowly swaying mass overhead. Two warped octaves so
  // the leaves overlap instead of tiling.
  vec2 sway = vec2(sin(t * 0.35) * 0.05, cos(t * 0.27) * 0.03);
  vec2 cq = p * uNoiseScale * 1.7 + sway;
  float leaves = fbm(cq + fbm(cq * 0.6 + uSeed) * 0.9);
  col = mix(col, uColorB, smoothstep(0.35, 0.8, leaves)
                          * smoothstep(0.9, 0.1, uv.y) * 0.55);

  // DAPPLED SHAFTS. Gaps in that same canopy field let light through, so the
  // dapple and the leaves agree with each other rather than being two
  // unrelated layers.
  float gap = smoothstep(0.62, 0.9, 1.0 - leaves);
  float fall = smoothstep(1.0, 0.15, uv.y);
  col += uColorC * gap * fall * 0.5 * uIntensity;

  // A few broad shafts sloping down, brightest near the top.
  float shaft = pow(0.5 + 0.5 * sin(p.x * 4.0 - uv.y * 2.2 + t * 0.15), 8.0);
  col += uColorC * shaft * fall * 0.16 * uIntensity;

  // DEPTH — the crypt is a forest, and a forest has things standing in it.
  // Two ranks of trunk silhouettes: a far rank washed out by the haze between
  // them and the viewer, and a near rank almost black. Without these the
  // canopy is a ceiling with no room under it, which is what made this planet
  // read as flat green noise.
  for (int rank = 0; rank < 2; rank++) {
    float fr = float(rank);
    float freq = 2.2 + fr * 2.6;
    // Irregular spacing: real trunks are not a picket fence.
    float jitter = fbm(vec2(floor(p.x * freq), fr * 13.0)) * 0.45;
    float bar = abs(fract(p.x * freq + jitter) - 0.5);
    // Trunks taper and lean very slightly, and they only occupy the lower
    // two thirds — above that they are canopy, not trunk.
    float lean = (uv.y - 0.5) * 0.05 * (fr * 2.0 - 1.0);
    float width = 0.055 - fr * 0.018 + uv.y * 0.02;
    float trunk = smoothstep(width, width * 0.35, bar + lean)
                * smoothstep(0.18, 0.62, uv.y);
    // Far rank sits in the haze; near rank eats the light.
    vec3 trunkCol = mix(uColorB * 0.35, uColorA * 0.5, fr);
    col = mix(col, trunkCol, trunk * (0.30 + fr * 0.45));
  }

  // Undergrowth catching the light along the very bottom edge.
  float under = fbm(vec2(p.x * 5.0 + t * 0.05, p.y * 3.0) + 77.0);
  col = mix(col, uColorB * 0.7,
            smoothstep(0.86, 1.0, uv.y) * smoothstep(0.35, 0.8, under) * 0.55);

  // Pollen: slow, warm, and it drifts UP and sideways in the light.
  for (int layer = 0; layer < 2; layer++) {
    float fl = float(layer);
    float scale = 28.0 + fl * 22.0;
    vec2 gg = vec2(p.x + sin(t * 0.5 + fl * 2.0) * 0.06,
                   p.y - t * (0.04 + fl * 0.03)) * scale;
    vec2 cc = floor(gg);
    float rr = hash(cc + uSeed + fl * 5.5);
    float dd = length(fract(gg) - vec2(hash(cc + 3.3), hash(cc + 7.7)));
    float glow = 0.5 + 0.5 * sin(t * 2.0 + rr * 22.0);
    col += uColorC * step(0.980, rr) * smoothstep(0.10, 0.0, dd)
         * glow * (0.30 - fl * 0.1);
  }

  col *= 1.0 - smoothstep(0.55, 1.05, length(uv - vec2(0.5, 0.55))) * 0.4;
  fragColor = vec4(col, 1.0);
}
