// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/poison.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// POISON — Toxivyre, the Venom Monastery. Contagion you can SEE hanging in
// the air: heavy miasma settling into flat banks the way cold gas does, spore
// motes tumbling slowly through it, and a faint bubbling where something is
// rotting below. Sickly and STILL — the opposite of Lightning's flicker and
// Lava's flow. uColorA rot-dark, uColorB venous green, uColorC spore pallor.
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  // Gas is heavy: darkest and thickest at the floor, thinning upward.
  vec3 col = mix(uColorB, uColorA, smoothstep(0.15, 1.0, uv.y));

  // Miasma banks — deliberately FLATTENED on y so the fog lies in strata
  // instead of billowing. Slow enough to look like it is settling, not moving.
  vec2 q = vec2(p.x * 0.8, p.y * 3.4) * uNoiseScale + vec2(t * 0.06, -t * 0.02);
  float bank = fbm(q);
  col = mix(col, uColorB, smoothstep(0.42, 0.78, bank) * 0.5);

  // A second, thinner veil drifting the other way, so the air has depth.
  float veil = fbm(vec2(p.x * 1.1 - t * 0.04, p.y * 2.2) * uNoiseScale + 21.0);
  col = mix(col, uColorC * 0.55, smoothstep(0.55, 0.92, veil) * 0.18);

  // Rot bubbles rising from the floor: they swell, then are gone.
  for (int layer = 0; layer < 2; layer++) {
    float fl = float(layer);
    float scale = 22.0 + fl * 14.0;
    vec2 gg = vec2(p.x, p.y + t * (0.05 + fl * 0.03)) * scale;
    vec2 cc = floor(gg);
    float rr = hash(cc + uSeed + fl * 6.1);
    float isBub = step(0.986, rr);
    vec2 mp = vec2(hash(cc + 1.3), hash(cc + 4.7));
    float dd = length(fract(gg) - mp);
    // Swell and pop rather than twinkle.
    float swell = fract(t * 0.35 + rr);
    float rad = 0.02 + swell * 0.07;
    float ring = smoothstep(rad, rad * 0.55, dd) * (1.0 - swell);
    // Only near the floor — gas does not bubble out of the ceiling.
    col += uColorC * isBub * ring * smoothstep(0.25, 1.0, uv.y) * 0.5;
  }

  // Spore motes: slow, tumbling, and they FALL. Nothing here rises cleanly.
  vec2 gg = vec2(p.x + sin(t * 0.4 + p.y * 3.0) * 0.05, p.y - t * 0.03) * 34.0;
  vec2 cc = floor(gg);
  float rr = hash(cc + uSeed);
  float dd = length(fract(gg) - vec2(hash(cc + 3.7), hash(cc + 8.1)));
  col += uColorC * step(0.985, rr) * smoothstep(0.10, 0.0, dd) * 0.35 * uIntensity;

  col *= 1.0 - smoothstep(0.5, 1.0, length(uv - 0.5)) * 0.42;
  fragColor = vec4(col, 1.0);
}
