// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/spirit.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// SPIRIT — Requia, the Echo Grave. The planet's whole idea is one place read
// twice, so the background is DOUBLED: the same field sampled at two offsets
// and laid over itself, one lagging the other like an afterimage. Wisps drift
// through it and a cold veil breathes across the frame. Pale and weightless —
// nothing here is solid. uColorA grave dark, uColorB spectral cyan,
// uColorC wisp white.
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  vec3 col = mix(uColorA, uColorB * 0.4, smoothstep(1.1, 0.0, uv.y));

  // THE TWO WORLDS. One field, sampled twice with a small spatial and
  // temporal offset. Where they agree the air is quiet; where they disagree
  // you get the ghost fringe that gives the planet its look.
  vec2 q = p * uNoiseScale * 1.5 + vec2(t * 0.05, -t * 0.03);
  float living = fbm(q);
  float ghost = fbm(q + vec2(0.09, -0.05));
  col = mix(col, uColorB, smoothstep(0.45, 0.85, living) * 0.34);
  // The lagging copy is written as a cold rim, not a second cloud.
  col += uColorC * smoothstep(0.05, 0.0, abs(living - ghost) - 0.03) * 0.22;

  // A veil breathing across the whole frame — the grave inhaling.
  float breath = 0.5 + 0.5 * sin(t * 0.5);
  col = mix(col, uColorB * 0.9, smoothstep(0.6, 1.0, fbm(q * 0.5 + 29.0))
                                * breath * 0.2);

  // Wisps: they rise, wander, and fade in and out of existence entirely.
  for (int layer = 0; layer < 2; layer++) {
    float fl = float(layer);
    float scale = 20.0 + fl * 16.0;
    vec2 gg = vec2(p.x + sin(t * 0.6 + fl * 3.0 + p.y * 4.0) * 0.07,
                   p.y - t * (0.05 + fl * 0.035)) * scale;
    vec2 cc = floor(gg);
    float rr = hash(cc + uSeed + fl * 8.2);
    float dd = length(fract(gg) - vec2(hash(cc + 4.1), hash(cc + 9.3)));
    // Presence comes and goes on its own slow cycle — a wisp is not always
    // there, which is what separates these from Lightning's steady motes.
    float here = smoothstep(0.35, 0.9, sin(t * 0.7 + rr * 18.0) * 0.5 + 0.5);
    col += mix(uColorB, uColorC, fl) * step(0.978, rr)
         * smoothstep(0.13, 0.0, dd) * here * 0.45 * uIntensity;
  }

  col *= 1.0 - smoothstep(0.5, 1.0, length(uv - 0.5)) * 0.44;
  fragColor = vec4(col, 1.0);
}
