// GENERATED by tool/build_dungeon_shaders.dart — DO NOT EDIT.
// Edit assets/shaders/dungeon/elements/steam.src.frag or common/*.glsl, then re-run the tool.

// Dungeon background shader — shared header + uniform contract.
// Every elemental shader uses THIS exact uniform interface (same setFloat order
// on the Dart side). Output is background-only; no gameplay logic here.
#include <flutter/runtime_effect.glsl>

out vec4 fragColor;

uniform vec2 uResolution;  // 0,1
uniform float uTime;       // 2
uniform vec3 uColorA;      // 3,4,5   (zenith / base)
uniform vec3 uColorB;      // 6,7,8   (horizon / mid)
uniform vec3 uColorC;      // 9,10,11 (highlight / energy)
uniform float uIntensity;  // 12
uniform float uNoiseScale; // 13
uniform float uFlowSpeed;  // 14
uniform float uSeed;       // 15

// Shared value-noise + fbm (same as fire.frag's proven helpers).
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  vec2 u = f * f * (3.0 - 2.0 * f);
  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}

float fbm(vec2 p) {
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++) {
    v += a * noise(p);
    p *= 2.0;
    a *= 0.5;
  }
  return v;
}

// Shared palette helpers. Mixes the three contract colours by a 0..1 ramp.
vec3 palette3(float t, vec3 a, vec3 b, vec3 c) {
  t = clamp(t, 0.0, 1.0);
  return t < 0.5 ? mix(a, b, t * 2.0) : mix(b, c, (t - 0.5) * 2.0);
}

// Normalised pixel UV (0..1), origin top-left.
vec2 dungeonUV() {
  return FlutterFragCoord().xy / uResolution;
}

// STEAM — Vaporis, the Pressure Cathedral. The inside of a great boiler-works:
// rising columns of hot mist, a heavy iron gloom, pressure-shimmer warping the
// air, furnace-light pooling low, and a slow tidal pulse like the breath of the
// machine. Body only: the shared header/helpers are prepended by
// tool/build_dungeon_shaders.dart. Uses uColorA (iron dark), uColorB (steam
// grey-white), uColorC (furnace ember).
void main() {
  vec2 uv = dungeonUV();
  float aspect = uResolution.x / max(uResolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  float t = uTime * uFlowSpeed;

  // Iron gloom — darkest at the top girders, a faint furnace warmth pooling low.
  vec3 base = mix(uColorA, uColorA * 1.35, smoothstep(0.0, 1.1, uv.y));
  base = mix(base, uColorC * 0.5, smoothstep(0.78, 1.0, uv.y) * 0.35);

  // Pressure shimmer: warp the sampling so the mist columns waver like heat-haze.
  float shimmer = fbm(p * uNoiseScale * 2.0 + vec2(0.0, -t * 0.4));
  vec2 warp = vec2(shimmer - 0.5, 0.0) * 0.08;

  // Rising steam columns — vertical fbm scrolling upward, brighter where dense.
  vec2 q = (p + warp) * vec2(uNoiseScale * 1.1, uNoiseScale * 0.7)
           + vec2(t * 0.03, -t * 0.5);
  float steam = fbm(q);
  steam = smoothstep(0.45, 0.95, steam);
  vec3 col = mix(base, uColorB, steam * 0.55);

  // A second, slower veil for depth.
  float veil = fbm((p + warp) * uNoiseScale * 0.8 + vec2(-t * 0.02, -t * 0.22));
  col = mix(col, uColorB * 0.9, smoothstep(0.6, 1.0, veil) * 0.22);

  // The machine's breath: a slow brightness pulse across the whole frame.
  float breath = 0.5 + 0.5 * sin(t * 0.5);
  col += uColorB * breath * 0.04 * uIntensity;

  // Condensation droplets sliding down, catching furnace-light.
  for (int layer = 0; layer < 2; layer++) {
    float fl = float(layer);
    float scale = 26.0 + fl * 16.0;
    float fall = t * (0.05 + fl * 0.03);
    vec2 gg = vec2(p.x, p.y - fall) * scale;
    vec2 cc = floor(gg);
    vec2 ff = fract(gg);
    float rr = hash(cc + uSeed + fl * 8.3);
    float isDrop = step(0.988, rr);
    vec2 dp = vec2(hash(cc + 1.9), hash(cc + 3.3));
    float dd = length(ff - dp);
    float drop = isDrop * smoothstep(0.10, 0.0, dd);
    col += mix(uColorB, uColorC, fl * 0.5) * drop * (0.2 + 0.1 * fl) * uIntensity;
  }

  // Furnace embers drifting up from below, fading as they rise.
  vec2 eg = p * 34.0 + vec2(sin(t * 0.6) * 0.4, t * 0.8);
  vec2 ec = floor(eg);
  vec2 ef = fract(eg);
  float er = hash(ec + uSeed + 5.1);
  float isEmber = step(0.992, er);
  float ed = length(ef - vec2(0.5));
  float ember = isEmber * smoothstep(0.12, 0.0, ed) * smoothstep(0.0, 0.6, uv.y);
  col += uColorC * ember * 0.5 * uIntensity;

  // Heavy vault vignette.
  col *= 1.0 - smoothstep(0.5, 1.0, length(uv - 0.5)) * 0.4;

  fragColor = vec4(col, 1.0);
}
