// lib/games/heart_puzzle/heart_puzzle_levels.dart
//
// GENERATED by tool/heart_puzzle_search.dart — found by search and
// proved; test/heart_puzzle_test.dart holds each to its par and its
// one way. The way is written above each level.

import 'package:alchemons/games/heart_puzzle/heart_puzzle_rules.dart';

class AltarChapter {
  const AltarChapter(this.name, this.first, this.last);
  final String name;
  final int first, last;
}

const List<AltarChapter> kAltarChapters = [
  AltarChapter('Basics', 1, 3),
  AltarChapter('Rising', 4, 11),
  AltarChapter('The Split', 12, 20),
  AltarChapter('Species', 21, 29),
  AltarChapter('Stacks', 30, 37),
  AltarChapter('Blood', 38, 45),
];

const List<AltarLevel> kAltarLevels = [
  // ── Basics ──
  // 1. par 1 — the altar: two make one.
  //   Fire + Water → Steam, the goal
  AltarLevel(goal: 'Steam', hand: ['Fire', 'Water'], columns: [[]], par: 1),
  // 2. par 1 — what is made rises, and fuses with what hangs above.
  //   Air + Fire → Lightning on altar 1, meets Earth → Crystal
  AltarLevel(
    goal: 'Crystal',
    hand: ['Air', 'Fire'],
    columns: [
      ['Earth'],
    ],
    par: 1,
  ),
  // 3. par 2 — every orb must be taken: Lava at once leaves the Dust
  // hanging for good, so the Earth first goes up into it and comes back.
  //   Earth + Water → Mud on altar 2, meets Dust → Earth
  //   Earth + Fire → Lava, the goal
  AltarLevel(
    goal: 'Lava',
    hand: ['Fire', 'Water', 'Earth'],
    columns: [
      [],
      ['Dust'],
    ],
    par: 2,
  ),
  // ── Rising ──
  // 4. par 2, 5 states
  //   Fire + Water → Steam on altar 1
  //   Dust + Steam → Water on altar 1, meets Earth → Mud
  AltarLevel(
    goal: 'Mud',
    hand: ['Water', 'Fire', 'Dust'],
    columns: [
      ['Earth'],
    ],
    par: 2,
  ),
  // 5. par 2, 5 states
  //   Earth + Water → Mud on altar 1, meets Light → Plant
  //   Fire + Plant → Dust, the goal
  AltarLevel(
    goal: 'Dust',
    hand: ['Water', 'Fire', 'Earth'],
    columns: [
      ['Light'],
    ],
    par: 2,
  ),
  // 6. par 3, 11 states
  //   Earth + Lightning → Crystal on altar 1, meets Spirit → Light
  //   Dust + Water → Earth on altar 1
  //   Earth + Light → Plant, the goal
  AltarLevel(
    goal: 'Plant',
    hand: ['Lightning', 'Water', 'Earth', 'Dust'],
    columns: [
      ['Spirit'],
    ],
    par: 3,
  ),
  // 7. par 3, 11 states
  //   Air + Ice → Water on altar 1
  //   Dust + Water → Earth on altar 1
  //   Earth + Fire → Lava on altar 1, meets Mud → Poison
  AltarLevel(
    goal: 'Poison',
    hand: ['Dust', 'Fire', 'Air', 'Ice'],
    columns: [
      ['Mud'],
    ],
    par: 3,
  ),
  // 8. par 3, 11 states
  //   Dust + Steam → Water on altar 1, meets Fire → Steam
  //   Earth + Lightning → Crystal on altar 1
  //   Air + Crystal → Ice, the goal
  AltarLevel(
    goal: 'Ice',
    hand: ['Steam', 'Dust', 'Lightning', 'Earth', 'Air'],
    columns: [
      ['Fire'],
    ],
    par: 3,
  ),
  // 9. par 3, 12 states
  //   Air + Ice → Water on altar 2
  //   Dust + Water → Earth on altar 1, meets Fire → Lava
  //   Air + Lava → Fire, the goal
  AltarLevel(
    goal: 'Fire',
    hand: ['Air', 'Dust', 'Ice', 'Air'],
    columns: [
      ['Fire'],
      [],
    ],
    par: 3,
  ),
  // 10. par 4, 32 states
  //   Dust + Water → Earth on altar 1, meets Light → Plant
  //   Fire + Ice → Water on altar 1
  //   Plant + Water → Mud on altar 1
  //   Fire + Mud → Lava, the goal
  AltarLevel(
    goal: 'Lava',
    hand: ['Water', 'Fire', 'Ice', 'Fire', 'Dust'],
    columns: [
      ['Light'],
    ],
    par: 4,
  ),
  // 11. par 4, 39 states
  //   Air + Mud → Dust on altar 1, meets Steam → Water
  //   Dust + Water → Earth on altar 1
  //   Earth + Fire → Lava on altar 1
  //   Lava + Mud → Poison, the goal
  AltarLevel(
    goal: 'Poison',
    hand: ['Fire', 'Mud', 'Air', 'Mud', 'Dust'],
    columns: [
      ['Steam'],
    ],
    par: 4,
  ),
  // ── The Split ──
  // 12. par 3, 11 states, longer: 4/5
  //   Earth + Lightning → Crystal on altar 1, meets Spirit → Light
  //   split Light
  //   Fire + Spirit → Steam, the goal
  AltarLevel(
    goal: 'Steam',
    hand: ['Lightning', 'Fire', 'Earth', 'Fire'],
    columns: [
      ['Spirit'],
    ],
    split: true,
    par: 3,
  ),
  // 13. par 3, 12 states, longer: 4
  //   Earth + Spirit → Crystal on altar 1, meets Air → Ice
  //   split Ice
  //   Air + Lava → Fire on altar 1
  AltarLevel(
    goal: 'Fire',
    hand: ['Lava', 'Earth', 'Spirit'],
    columns: [
      ['Air'],
    ],
    split: true,
    par: 3,
  ),
  // 14. par 4, 31 states, longer: 5/6
  //   Air + Water → Ice on altar 1
  //   Air + Ice → Water on altar 1, meets Spirit → Ice
  //   split Ice
  //   Crystal + Spirit → Light, the goal
  AltarLevel(
    goal: 'Light',
    hand: ['Air', 'Air', 'Crystal', 'Water'],
    columns: [
      ['Spirit'],
    ],
    split: true,
    par: 4,
  ),
  // 15. par 5, 30 states, longer: 6/7
  //   Crystal + Spirit → Light on altar 1, meets Dark → Blood
  //   split Blood
  //   Dark + Plant → Poison, the goal
  //   split Light
  //   Crystal + Lightning → Spirit on altar 1, meets Fire → Steam
  AltarLevel(
    goal: 'Poison',
    hand: ['Plant', 'Spirit', 'Lightning', 'Crystal'],
    columns: [
      ['Dark', 'Fire'],
    ],
    split: true,
    par: 5,
  ),
  // 16. par 5, 72 states, longer: 6/7
  //   Poison + Spirit → Dark on altar 1, meets Water → Spirit
  //   split Spirit
  //   Dark + Water → Spirit on altar 1, meets Earth → Crystal
  //   split Crystal
  //   Earth + Spirit → Crystal on altar 2, meets Spirit → Light
  AltarLevel(
    goal: 'Light',
    hand: ['Poison', 'Fire', 'Spirit', 'Mud'],
    columns: [
      ['Water', 'Earth'],
      ['Spirit'],
    ],
    split: true,
    par: 5,
  ),
  // 17. par 5, 74 states, longer: 7
  //   Dark + Plant → Poison on altar 2, meets Ice → Crystal
  //   split Crystal
  //   Poison + Spirit → Dark on altar 1, meets Water → Spirit
  //   split Spirit
  //   Dark + Water → Spirit on altar 2, meets Air → Lightning
  AltarLevel(
    goal: 'Lightning',
    hand: ['Spirit', 'Dark', 'Plant'],
    columns: [
      ['Water'],
      ['Ice', 'Air'],
    ],
    split: true,
    par: 5,
  ),
  // 18. par 6, 94 states, longer: 7
  //   Air + Lava → Fire on altar 1, meets Ice → Water
  //   Air + Water → Ice on altar 2, meets Lava → Steam
  //   split Steam
  //   split Ice
  //   split Water
  //   Air + Fire → Lightning on altar 1, meets Crystal → Spirit
  AltarLevel(
    goal: 'Spirit',
    hand: ['Lava', 'Air', 'Air'],
    columns: [
      ['Ice', 'Crystal'],
      ['Lava'],
    ],
    split: true,
    par: 6,
  ),
  // 19. par 7, 54 states, longer: 8/9
  //   Ice + Poison → Crystal on altar 2, meets Spirit → Light
  //   split Light
  //   split Crystal
  //   Poison + Spirit → Dark on altar 1, meets Water → Spirit
  //   split Spirit
  //   Plant + Water → Mud on altar 1, meets Lava → Poison
  //   split Poison
  AltarLevel(
    goal: 'Lava',
    hand: ['Ice', 'Plant', 'Poison'],
    columns: [
      ['Water', 'Lava'],
      ['Spirit'],
    ],
    split: true,
    par: 7,
  ),
  // 20. par 7, 57 states, longer: 8/9
  //   Light + Poison → Fire on altar 1
  //   Fire + Spirit → Steam on altar 1, meets Dust → Water
  //   Spirit + Water → Ice on altar 1, meets Water → Steam
  //   split Steam
  //   split Ice
  //   split Water
  //   Dust + Water → Earth, the goal
  AltarLevel(
    goal: 'Earth',
    hand: ['Poison', 'Light', 'Spirit', 'Spirit'],
    columns: [
      ['Dust', 'Water'],
    ],
    split: true,
    par: 7,
  ),
  // ── Species ──
  // 21. par 2, 21 states, longer: 3
  //   Dust Horn + Water Mask → Earth Mane on altar 1
  //   Earth Mane + Lightning Horn → Crystal Mask, the goal
  AltarLevel(
    goal: 'Crystal',
    goalFamily: 'Mask',
    hand: [
      'Lightning Horn',
      'Dust Horn',
      'Fire Horn',
      'Water Mask',
      'Earth Horn',
    ],
    columns: [[]],
    species: true,
    par: 2,
  ),
  // 22. par 2, 21 states, longer: 3
  //   Dust Horn + Steam Mane → Water Mask on altar 1
  //   Earth + Water Mask → Mud Pip, the goal
  AltarLevel(
    goal: 'Mud',
    goalFamily: 'Pip',
    hand: ['Dust Horn', 'Water Horn', 'Earth', 'Fire', 'Steam Mane'],
    columns: [[]],
    species: true,
    par: 2,
  ),
  // 23. par 2, 21 states, longer: 3
  //   Dust + Steam → Water Pip on altar 1
  //   Earth Mask + Water Pip → Mud, the goal
  AltarLevel(
    goal: 'Mud',
    goalFamily: 'Let',
    hand: ['Water', 'Steam', 'Fire Horn', 'Dust', 'Earth Mask'],
    columns: [[]],
    species: true,
    par: 2,
  ),
  // 24. par 2, 22 states, longer: 3
  //   Fire + Mud Mane → Lava Horn on altar 1
  //   Ice + Lava Horn → Steam Mane, the goal
  AltarLevel(
    goal: 'Steam',
    goalFamily: 'Mane',
    hand: ['Fire', 'Water Mask', 'Mud Mane', 'Fire Pip', 'Ice'],
    columns: [[]],
    species: true,
    par: 2,
  ),
  // 25. par 2, 22 states, longer: 3
  //   Air Horn + Water Horn → Ice Horn on altar 1, meets Poison → Crystal Horn
  //   Crystal Horn + Lava → Earth Mane, the goal
  AltarLevel(
    goal: 'Earth',
    goalFamily: 'Mane',
    hand: ['Air Horn', 'Water', 'Water Horn', 'Fire Mask', 'Lava'],
    columns: [
      ['Poison'],
    ],
    species: true,
    par: 2,
  ),
  // 26. par 3, 28 states, longer: 4
  //   Air + Water Pip → Ice Mask on altar 1, meets Air → Water Mask
  //   Dust + Water Mask → Earth Pip on altar 1
  //   Earth Pip + Lightning Pip → Crystal Pip, the goal
  AltarLevel(
    goal: 'Crystal',
    goalFamily: 'Pip',
    hand: ['Water Pip', 'Dust', 'Earth Mask', 'Air', 'Lightning Pip'],
    columns: [
      ['Air'],
    ],
    species: true,
    par: 3,
  ),
  // 27. par 3, 28 states, longer: 4
  //   Earth Pip + Lightning Mask → Crystal on altar 1
  //   Crystal + Lava Horn → Earth Mane on altar 1
  //   Air Mask + Earth Mane → Dust Pip, the goal
  AltarLevel(
    goal: 'Dust',
    goalFamily: 'Pip',
    hand: [
      'Lightning Mask',
      'Water Mane',
      'Lava Horn',
      'Earth Pip',
      'Air Mask',
    ],
    columns: [[]],
    species: true,
    par: 3,
  ),
  // 28. par 3, 33 states, longer: 4
  //   Fire Horn + Ice → Water Mane on altar 1
  //   Earth Horn + Water Mane → Mud Mask on altar 1
  //   Fire Mane + Mud Mask → Lava Pip, the goal
  AltarLevel(
    goal: 'Lava',
    goalFamily: 'Pip',
    hand: ['Dust Mask', 'Ice', 'Fire Horn', 'Earth Horn', 'Fire Mane'],
    columns: [[]],
    species: true,
    par: 3,
  ),
  // 29. par 3, 35 states, longer: 4
  //   Air Mane + Lava Horn → Fire Mask on altar 1
  //   Fire Mask + Ice Mask → Water Mask on altar 1
  //   Ice + Water Mask → Steam Pip on altar 1
  AltarLevel(
    goal: 'Steam',
    goalFamily: 'Pip',
    hand: ['Lava Horn', 'Mud Mane', 'Ice', 'Air Mane', 'Ice Mask'],
    columns: [[]],
    species: true,
    par: 3,
  ),
  // ── Stacks ──
  // 30. par 4, 80 states, longer: 6
  //   Lava + Mud Mask → Poison Pip on altar 1, meets Ice → Crystal Pip
  //   split Crystal Pip
  //   Ice + Poison Pip → Crystal Mask on altar 3, meets Spirit → Light Mask
  //   Light Mask + Spirit Mask → Air Mask on altar 2, meets Water → Ice Mask
  AltarLevel(
    goal: 'Ice',
    goalFamily: 'Mask',
    hand: ['Mud Mask', 'Spirit Mask', 'Lava'],
    columns: [
      ['Ice'],
      ['Water'],
      ['Spirit'],
    ],
    split: true,
    species: true,
    par: 4,
  ),
  // 31. par 5, 133 states, longer: 6/7
  //   Light Mane + Spirit Pip → Air Mask on altar 1, meets Fire → Lightning Mask
  //   split Lightning Mask
  //   Fire + Mud Mask → Lava Pip on altar 1, meets Crystal → Earth Pip
  //   split Earth Pip
  //   Crystal + Lava Pip → Earth Mask on altar 2, meets Fire → Lava Mask
  AltarLevel(
    goal: 'Lava',
    goalFamily: 'Mask',
    hand: ['Spirit Pip', 'Mud Mask', 'Light Mane'],
    columns: [
      ['Fire', 'Crystal'],
      ['Fire'],
    ],
    split: true,
    species: true,
    par: 5,
  ),
  // 32. par 5, 139 states, longer: 7
  //   Fire Pip + Ice Mask → Water on altar 2, meets Plant → Mud
  //   split Mud
  //   Plant + Water → Mud Pip on altar 2, meets Plant → Poison Pip
  //   split Poison Pip
  //   Fire + Mud Pip → Lava Mask on altar 1, meets Crystal → Earth Mask
  AltarLevel(
    goal: 'Earth',
    goalFamily: 'Mask',
    hand: ['Fire Pip', 'Ice Mask', 'Fire'],
    columns: [
      ['Crystal'],
      ['Plant', 'Plant'],
    ],
    split: true,
    species: true,
    par: 5,
  ),
  // 33. par 6, 255 states, longer: 7
  //   Air Mane + Mud → Dust Horn on altar 2, meets Water → Earth Horn
  //   split Earth Horn
  //   Plant Mane + Water → Mud Horn on altar 2, meets Light → Plant Horn
  //   split Dust Horn
  //   split Plant Horn
  //   Air Mane + Mud Horn → Dust Mask on altar 1, meets Mud → Earth Mask
  AltarLevel(
    goal: 'Earth',
    goalFamily: 'Mask',
    hand: ['Plant Mane', 'Mud', 'Air Mane'],
    columns: [
      ['Mud'],
      ['Water', 'Light'],
    ],
    split: true,
    species: true,
    par: 6,
  ),
  // 34. par 6, 302 states, longer: 7/8
  //   Plant + Water → Mud Pip on altar 2, meets Lava → Poison Pip
  //   Earth + Poison → Lava Pip on altar 2, meets Air → Fire Pip
  //   split Poison Pip
  //   split Fire Pip
  //   Air + Lava → Fire Pip on altar 1, meets Water → Steam Pip
  //   Lava Pip + Mud Pip → Poison Pip on altar 1, meets Spirit → Dark Pip
  AltarLevel(
    goal: 'Steam',
    goalFamily: 'Pip',
    hand: ['Plant', 'Poison', 'Water', 'Earth'],
    columns: [
      ['Water', 'Spirit'],
      ['Lava', 'Air'],
    ],
    split: true,
    species: true,
    par: 6,
  ),
  // 35. par 7, 290 states, longer: 9
  //   Light + Poison → Fire Pip on altar 1, meets Air → Lightning Pip
  //   split Lightning Pip
  //   Fire Pip + Spirit → Steam Mask on altar 2, meets Dust → Water Mask
  //   split Water Mask
  //   Dust + Steam Mask → Water Pip on altar 3, meets Dark → Spirit Pip
  //   split Spirit Pip
  //   Air + Water Pip → Ice Mask on altar 3, meets Poison → Crystal Mask
  AltarLevel(
    goal: 'Crystal',
    goalFamily: 'Mask',
    hand: ['Poison', 'Spirit', 'Spirit Pip', 'Light'],
    columns: [
      ['Air'],
      ['Dust'],
      ['Dark', 'Poison'],
    ],
    split: true,
    species: true,
    par: 7,
  ),
  // 36. par 7, 320 states, longer: 8/9
  //   Air + Water → Ice Pip on altar 1, meets Light → Air Pip
  //   split Air Pip
  //   Air + Ice Pip → Water Mask on altar 2, meets Earth → Mud Mask
  //   Light + Mud Mask → Plant Pip on altar 1, meets Mud → Poison Pip
  //   split Poison Pip
  //   Mud + Plant Pip → Poison Mask on altar 2, meets Ice → Crystal Mask
  //   split Crystal Mask
  AltarLevel(
    goal: 'Ice',
    goalFamily: 'Let',
    hand: ['Air', 'Air', 'Water'],
    columns: [
      ['Light', 'Mud'],
      ['Earth', 'Ice'],
    ],
    split: true,
    species: true,
    par: 7,
  ),
  // 37. par 8, 260 states, longer: 10
  //   Lightning + Plant Pip → Fire Mask on altar 1, meets Spirit → Steam Mask
  //   split Steam Mask
  //   Light + Spirit → Air Pip on altar 1, meets Spirit → Lightning Pip
  //   split Lightning Pip
  //   Air Pip + Fire Mask → Lightning on altar 2, meets Plant → Fire
  //   Fire + Spirit → Steam Pip on altar 2, meets Dust → Water Pip
  //   split Water Pip
  //   split Steam Pip
  AltarLevel(
    goal: 'Fire',
    goalFamily: 'Let',
    hand: ['Light', 'Plant Pip', 'Lightning'],
    columns: [
      ['Spirit', 'Spirit'],
      ['Plant', 'Dust'],
    ],
    split: true,
    species: true,
    par: 8,
  ),
  // ── Blood ──
  // 38. par 5, 364 states, longer: 7
  //   Crystal + Spirit → Light Pip on altar 1, meets Earth → Plant Pip
  //   split Plant Pip
  //   Earth + Light Pip → Plant Mask on altar 2, meets Water → Mud Mask
  //   Mud Mask + Plant Mask → Poison Mask on altar 1, meets Spirit → Dark Mask
  //   Dark Mask + Light Pip → Blood on altar 1
  AltarLevel(
    goal: 'Blood',
    hand: ['Light Pip', 'Spirit', 'Crystal', 'Plant Mask'],
    columns: [
      ['Earth', 'Spirit'],
      ['Water'],
    ],
    split: true,
    species: true,
    par: 5,
  ),
  // 39. par 6, 114 states, longer: 8
  //   Earth Mask + Water → Mud Pip on altar 1, meets Lava → Poison Pip
  //   split Poison Pip
  //   Lava + Mud Pip → Poison Mask on altar 2, meets Earth → Lava Mask
  //   split Lava Mask
  //   Earth + Lightning → Crystal Pip on altar 1, meets Lightning → Spirit Pip
  //   Poison Mask + Spirit Pip → Dark on altar 2, meets Light → Blood
  AltarLevel(
    goal: 'Blood',
    hand: ['Lightning', 'Water', 'Earth Mask'],
    columns: [
      ['Lava', 'Lightning'],
      ['Earth', 'Light'],
    ],
    split: true,
    species: true,
    par: 6,
  ),
  // 40. par 6, 534 states, longer: 7/8
  //   Earth Pip + Spirit → Crystal Mask on altar 1, meets Lava → Earth Mask
  //   split Earth Mask
  //   Air + Crystal Mask → Ice Pip on altar 1, meets Light → Air Pip
  //   split Air Pip
  //   Dark Pip + Light → Blood Mask, the goal
  //   Fire + Ice Pip → Water Mask on altar 2, meets Fire → Steam Mask
  AltarLevel(
    goal: 'Blood',
    hand: ['Air', 'Dark Pip', 'Fire', 'Earth Pip', 'Spirit'],
    columns: [
      ['Lava', 'Light'],
      ['Fire'],
    ],
    split: true,
    species: true,
    par: 6,
  ),
  // 41. par 7, 983 states, longer: 8/9
  //   Crystal Mask + Lightning → Spirit Pip on altar 2, meets Earth → Crystal Pip
  //   split Crystal Pip
  //   Earth + Spirit Pip → Crystal Mask on altar 1, meets Spirit → Light Mask
  //   Dark + Water → Spirit Pip on altar 1, meets Fire → Steam Pip
  //   split Steam Pip
  //   split Spirit Pip
  //   Dark + Light Mask → Blood Pip, the goal
  AltarLevel(
    goal: 'Blood',
    hand: ['Water', 'Crystal Mask', 'Dark', 'Lightning'],
    columns: [
      ['Spirit', 'Fire'],
      ['Earth'],
    ],
    split: true,
    species: true,
    par: 7,
  ),
  // 42. par 8, 59 states, longer: 10
  //   Air Pip + Ice → Water Mask on altar 2, meets Dark → Spirit Mask
  //   split Spirit Mask
  //   split Water Mask
  //   Air Pip + Mud → Dust Mask on altar 1, meets Mud → Earth Mask
  //   split Earth Mask
  //   Dust Mask + Mud → Earth Pip on altar 2, meets Lightning → Crystal Pip
  //   Crystal Pip + Spirit → Light Mask on altar 1
  //   Dark + Light Mask → Blood Pip, the goal
  AltarLevel(
    goal: 'Blood',
    hand: ['Air Pip', 'Ice', 'Mud', 'Spirit'],
    columns: [
      ['Mud'],
      ['Dark', 'Lightning'],
    ],
    split: true,
    species: true,
    par: 8,
  ),
  // 43. par 8, 879 states, longer: 9/10
  //   Air Pip + Mud Mask → Dust on altar 1, meets Water → Earth
  //   split Earth
  //   Dust + Water → Earth Pip on altar 2, meets Spirit → Crystal Pip
  //   split Crystal Pip
  //   Crystal + Spirit → Light Pip on altar 2, meets Spirit → Air Pip
  //   split Air Pip
  //   Poison Mask + Spirit → Dark Pip on altar 1
  //   Dark Pip + Light Pip → Blood Pip, the goal
  AltarLevel(
    goal: 'Blood',
    hand: ['Air Pip', 'Mud Mask', 'Poison Mask', 'Crystal'],
    columns: [
      ['Water'],
      ['Spirit', 'Spirit'],
    ],
    split: true,
    species: true,
    par: 8,
  ),
  // 44. par 9, 3613 states, longer: 11
  //   Earth Pip + Spirit → Crystal Mask on altar 1, meets Lightning → Spirit Mask
  //   split Spirit Mask
  //   Crystal Mask + Spirit → Light Pip on altar 2, meets Ice → Air Pip
  //   split Air Pip
  //   Air Pip + Ice → Water Mask on altar 2
  //   split Light Pip
  //   split Crystal Mask
  //   Earth Pip + Water Mask → Mud on altar 1, meets Plant → Poison
  //   Poison + Spirit → Dark Pip on altar 2, meets Light → Blood Pip
  AltarLevel(
    goal: 'Blood',
    hand: ['Spirit', 'Earth Pip', 'Spirit', 'Air Pip'],
    columns: [
      ['Lightning', 'Plant'],
      ['Ice', 'Light'],
    ],
    split: true,
    species: true,
    par: 9,
  ),
  // 45. par 10, 5678 states, longer: 11/12
  //   Plant + Water → Mud Pip on altar 1, meets Light → Plant Pip
  //   split Plant Pip
  //   Light + Poison Pip → Fire Mask on altar 2, meets Ice → Water Mask
  //   split Water Mask
  //   split Fire Mask
  //   Ice + Light → Air Pip on altar 2, meets Mud → Dust Pip
  //   Dust Pip + Mud Pip → Earth Pip on altar 1, meets Lightning → Crystal Pip
  //   split Crystal Pip
  //   Earth Pip + Lightning → Crystal Mask on altar 4, meets Lightning → Spirit Mask
  //   Poison Pip + Spirit Mask → Dark on altar 3, meets Light → Blood
  AltarLevel(
    goal: 'Blood',
    hand: ['Plant', 'Water', 'Poison Pip'],
    columns: [
      ['Light', 'Lightning'],
      ['Ice', 'Mud'],
      ['Light'],
      ['Lightning'],
    ],
    split: true,
    species: true,
    par: 10,
  ),
];
